default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        stages: [pre-commit]
        language_version: python3
        args: ["--config", "pyproject.toml", "wsjtxcli", "tests"]
        pass_filenames: false

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        stages: [pre-commit]
        args: ["--settings-path", "pyproject.toml", "wsjtxcli", "tests"]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        stages: [pre-commit]
        args: ["--config-file", "pyproject.toml", "wsjtxcli", "tests"]
        pass_filenames: false

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []